steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
    integrationFlowName: P2006255217-flow4
    packageId: test
    filePath: P2006255217-flow4.zip
  integrationArtifactUnDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
    downloadPath: P2006255217-flow4
    integrationFlowVersion: 1.0.3
  valueMappingArtifactDownload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    valueMappingId: test_mapping
    downloadPath: test_mapping
    valueMappingVersion: 1.0.1
    verbose: true
  valueMappingArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    valueMappingId: test_mapping_1
    valueMappingName: test_mapping_1
    packageId: test2
    filePath: test_mapping/test_mapping_1.zip
integrationPackageDownload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationPackageId: test
    downloadPath: CICD
    verbose: true
