steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
    integrationFlowName: P2006255217-flow4
    packageId: test
    filePath: P2006255217-flow4.zip
  integrationArtifactUnDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
  integrationArtifactDownload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: P2006255217-flow4
    downloadPath: P2006255217-flow4
    integrationFlowVersion: 1.0.2
  valueMappingArtifactDownload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: test_mapping
    downloadPath: test_mapping
    integrationFlowVersion: 1.0.1
